version: '3'

services:
  # React App
  react-app:
    image: node:14-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - api-server
 
# API Server
  api-server:
    image: node:14-alpine
    working_dir: /api
    ports:
      - "8080:8080"
    volumes:
      - ./server:/api
    command: sh -c "npm install && node server.js"